zap:
  level: info
  format: console
  prefix: '[kubernetesOperator:]'
  director: log
  link-name: latest_log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
system:
  env: public
  addr: 8888